### ISSUE TITLE
Consider using `users` crate

### ISSUE THREAD

**Issue by frol** [jedisct1/rust-privdrop#12]
https://crates.io/crates/users

P.S. Would you review a PR if I refactor the code using the `users` crate and introduce an API for the `std::process::Command`? (I will keep the existing public API unchanged)

**Comment by jedisct1** [comment]
But... why?

**Comment by frol** [comment]
To reuse a well-tested crate which does its work, and to drop 7 out of 8 unsafe blocks.

**Comment by jedisct1** [comment]
The `unsafe` blocks are just moved somewhere else. The libc functions we use here are very simple and portable, I don't think there is any value in doing the same thing via a dependency.
