### ISSUE TITLE
Released version (privdrop 0.3.1) doesn't compile on aarch64-unknown-linux-musl

### ISSUE THREAD

**Issue by oherrala** [jedisct1/rust-privdrop#13]
Compilation fails because `nix 0.11` has compilation issue with aarch64. This has been fixed and released I think in `nix 0.12` (https://github.com/nix-rust/nix/pull/912). I tested that the compilation works with privdrop's commit 771b0f6dafe178edd5518567919f9bb8741955c1 (which has `nix 0.13`).

The compilation error:

```
error[E0425]: cannot find value `MAP_32BIT` in module `libc`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.11.0/src/sys/mman.rs:53:9
   |
53 |         MAP_32BIT;
   |         ^^^^^^^^^ not found in `libc`
```

Please, can you release new version with newer dependency to `nix`?

**Comment by jedisct1** [comment]
Done.

**Comment by oherrala** [comment]
Thanks! 👍
