### ISSUE TITLE
Feature request: Linux capabilities

### ISSUE THREAD

**Issue by vi** [jedisct1/rust-privdrop#6]
On Linux, maybe it should also handle allowed, inherited and effective capability sets plus capability bounding and ambient sets.

Setting `PR_SET_NO_NEW_PRIVS` would also be fine.

**Comment by jedisct1** [comment]
I don't use Linux, but a pull request implementing this could be great.
OpenBSD's `pledge` would also be worth adding.

**Comment by vi** [comment]
Linux analogue of `pledge` seems to be [seccomp(2)](http://man7.org/linux/man-pages/man2/seccomp.2.html).
